### PR TITLE
improvement

### PR DESCRIPTION
**Pull request by halderen2**
objcopy exects for an Linux 64 bits machine -O elf64-x86-64 -b i386:x86-64

### CODE REVIEW

**Comment by halderen2** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
Pull request build failed

**Comment by halderen** [comment]
Pull request build failed

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
Pull request build failed

**Comment by halderen** [comment]
Pull request build failed

**Comment by halderen** [comment]
#build

**Pull request closed without merging**
